#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
# Taken from https://gist.github.com/ndarville/3625246

language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.7.9

before_install:
  - export DJANGO_SETTINGS_MODULE=dissemin.settings
  - export PYTHONPATH=$HOME/builds/wetneb/dissemin
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install -r requirements_frontend.txt
  - pip install -r requirements_backend.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate --noinput

