#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
# Taken from https://gist.github.com/ndarville/3625246

language: python

python:
  - 2.7

services:
  - postgresql
  - redis

sudo: false

addons:
    apt:
       packages:
       - python-numpy
       - python-scipy
       - python-requests
       - python-lxml

env:
  - DJANGO=1.7.9

virtualenv:
  system_site_packages: true

before_install:
  - export DJANGO_SETTINGS_MODULE=dissemin.settings
  - export PYTHONPATH=$HOME/builds/wetneb/dissemin
  - export PIP_USE_MIRRORS=true

install:
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet
  - pip install -r requirements_frontend_light.txt
  - pip install -r requirements_backend_light.txt
  - pip install coveralls
  - wget http://dev.dissem.in/files/similarity.pkl -O models/similarity.pkl

before_script:
  - psql -c "CREATE DATABASE dissemin;" -U postgres

script:
  - python manage.py migrate --noinput
  - coverage run --source=dissemin,papers,backend,deposit,upload,statistics manage.py test

after_success:
  - coveralls
